In [1]:
import pandas as pd
import numpy as np

# データ本体(センサー測定値)
data_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/secom/secom.data"
df_data = pd.read_csv(data_url, sep=' ', header=None)

# ラベル(Pass/Fail + タイムスタンプ)
labels_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/secom/secom_labels.data"
df_labels = pd.read_csv(labels_url, sep=' ', header=None, names=['label', 'timestamp'])

print(df_data.shape)
print(df_labels.shape)
df_data.head()

(1567, 590)
(1567, 2)

,0,1,2,3,4,5,6,7,8,9,...,580,581,582,583,584,585,586,587,588,589
0,3030.93,2564.00,2187.7333,1411.1265,1.3602,100.0,97.6133,0.1242,1.5005,0.0162,...,NaN,NaN,0.5005,0.0118,0.0035,2.3630,NaN,NaN,NaN,NaN
1,3095.78,2465.14,2230.4222,1463.6606,0.8294,100.0,102.3433,0.1247,1.4966,-0.0005,...,0.0060,208.2045,0.5019,0.0223,0.0055,4.4447,0.0096,0.0201,0.0060,208.2045
2,2932.61,2559.94,2186.4111,1698.0172,1.5102,100.0,95.4878,0.1241,1.4436,0.0041,...,0.0148,82.8602,0.4958,0.0157,0.0039,3.1745,0.0584,0.0484,0.0148,82.8602
3,2988.72,2479.90,2199.0333,909.7926,1.3204,100.0,104.2367,0.1217,1.4882,-0.0124,...,0.0044,73.8432,0.4990,0.0103,0.0025,2.0544,0.0202,0.0149,0.0044,73.8432
4,3032.24,2502.87,2233.3667,1326.5200,1.5334,100.0,100.3967,0.1235,1.5031,-0.0031,...,NaN,NaN,0.4800,0.4766,0.1045,99.3032,0.0202,0.0149,0.0044,73.8432

In [2]:
#欠損値の数を列ごとに集計し、多い順に　上位10列を表示
missing_counts = df_data.isnull().sum()
missing_counts.sort_values(ascending=False).head(10)

292    1429
293    1429
158    1429
157    1429
492    1341
85     1341
358    1341
220    1341
244    1018
517    1018
dtype: int64

In [8]:
#　欠損率を計算(0~1の比率　)
missing_rate=df_data.isnull().sum()/len(df_data)

#欠損率50%未満列のみ残す
threshold=0.5
df_clean=df_data.loc[:, missing_rate<threshold]

print(f"処理前:{df_data.shape}")
print(f"処理後:{df_clean.shape}")
print(f"削除した列数:{df_data.shape[1]-df_clean.shape[1]}")

処理前:(1567, 590)
処理後:(1567, 562)
削除した列数:28

In [9]:
#df_dataにlabelとtimestampを列として追加
df=df_clean.copy()
df['label']=df_labels['label']
df['timestamp']=df_labels['timestamp']

print(df.shape)
df[['label', 'timestamp']].head()

(1567, 564)

   label            timestamp
0     -1  19/07/2008 11:55:00
1     -1  19/07/2008 12:32:00
2      1  19/07/2008 13:17:00
3     -1  19/07/2008 14:43:00
4     -1  19/07/2008 15:22:00

In [10]:
#Pass/Fail件数と比率

In [12]:
label_counts=df['label'].value_counts()
label_ratio= df['label'].value_counts(normalize=True)*100

print("件数:")
print(label_counts)
print("\n比率(%):")
print(label_ratio.round(1))

件数:
label
-1    1463
 1     104
Name: count, dtype: int64

比率(%):
label
-1    93.4
 1     6.6
Name: proportion, dtype: float64